stages:
  - build
  - unit-tests
  - e2e-tests
  - deploy
  - portainer

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:10.0
  tags:
    - sopro
  script:
    - cd Trainee_Tracker
    - dotnet build

unit-tests:
  stage: unit-tests
  image: mcr.microsoft.com/dotnet/sdk:10.0
  tags:
    - sopro
  needs:
    - build
  script:
    - cd Trainee_Tracker.UnitTests
    - dotnet test

e2e-tests:
  stage: e2e-tests
  image: mcr.microsoft.com/dotnet/sdk:10.0
  tags:
    - sopro
  needs:
    - build
  script:
    - cd Trainee_Tracker
    
    
    - apt-get update -qq
    - apt-get install -y --no-install-recommends wget gnupg ca-certificates
    - wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt-get install -y --no-install-recommends ./google-chrome-stable_current_amd64.deb
    - rm google-chrome-stable_current_amd64.deb
    - google-chrome --version

    #DB reset
    - dotnet tool install --global dotnet-ef
    - export PATH="$PATH:/root/.dotnet/tools"

    - dotnet restore
    - dotnet build
    - mkdir -p Persistence
    - rm -f Persistence/trainee_tracker.db Persistence/trainee_tracker.db-wal Persistence/trainee_tracker.db-shm
    - dotnet ef database update

    - dotnet run --environment Development &

    # waiting
    - 
      for i in $(seq 1 30); do
        curl -sf http://localhost:5089 > /dev/null && break
        echo "App is not ready yet; waiting... ($i)"
        sleep 2
      done


    - cd ../Trainee_Tracker.E2ETests
    - dotnet test

deploy:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:v1.24.0-debug
    entrypoint: [ "" ]
  script:
    - echo "{\"auths\":{\"gitlab.isse.de:5050\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}" > /kaniko/.docker/config.jso
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/Trainee_Tracker"
      --dockerfile "${CI_PROJECT_DIR}/Trainee_Tracker/Dockerfile"
      --destination "gitlab.isse.de:5050/lehre/sopro/2026-sose/gruppen/team14/main:trainee_tracker"
  needs:
    - unit-tests
    - e2e-tests
  tags:
    - sopro
  only:
    refs:
      - main

portainer:
  stage: portainer
  image: curlimages/curl:latest
  tags:
    - sopro
  needs:
    - deploy
  script:
    - sleep 10
    - curl -X POST https://portainer.isse.de/api/webhooks/1774c4f4-c8c7-4161-a6a4-a2fe46b92e7b
  only:
    refs:
      - main
