stages:
  - build
  - unit-tests
  - e2e-tests
  - deploy
  - portainer

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:10.0
  tags:
    - sopro
  script:
    - cd Trainee_Tracker
    - dotnet build

unit-tests:
  stage: unit-tests
  image: mcr.microsoft.com/dotnet/sdk:10.0
  tags:
    - sopro
  needs:
    - build
  script:
    - cd Trainee_Tracker.UnitTests
    - dotnet test

e2e-tests:
  stage: e2e-tests
  image: mcr.microsoft.com/dotnet/sdk:10.0
  tags:
    - sopro
  needs:
    - build
  script:
    - cd Trainee_Tracker
    - dotnet run --environment Development &
    - apt-get update -qq
    - apt-get install -y --no-install-recommends wget gnupg ca-certificates
    - wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt-get install -y --no-install-recommends ./google-chrome-stable_current_amd64.deb
    - rm google-chrome-stable_current_amd64.deb
    - google-chrome --version
    - sleep 10
    - cd ../Trainee_Tracker.E2ETests
    - dotnet test

deploy:
  stage: deploy
  image: mcr.microsoft.com/dotnet/sdk:10.0
  tags:
    - sopro
  needs:
    - unit-tests
    - e2e-tests
  script:
    - echo "Deploying Trainee Tracker"
    - test -f Trainee_Tracker/Dockerfile
    - ls Trainee_Tracker

portainer:
  stage: portainer
  image: curlimages/curl:latest
  tags:
    - sopro
  needs:
    - deploy
  script:
    - sleep 10
    - curl -X POST "$CONTAINER_WEB_HOOK"