// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trainee_Tracker.Data;

#nullable disable

namespace Trainee_Tracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701094913_AddLessonFeedback")]
    partial class AddLessonFeedback
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("MentorTrainee", b =>
                {
                    b.Property<int>("AssignedTraineesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MentorsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssignedTraineesId", "MentorsId");

                    b.HasIndex("MentorsId");

                    b.ToTable("MentorTrainee");
                });

            modelBuilder.Entity("Trainee_Tracker.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Effort")
                        .HasColumnType("REAL");

                    b.Property<bool>("Inactive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            Effort = 1.0,
                            Inactive = false,
                            Position = 2,
                            Title = "Introduction to HTML",
                            URL = "#"
                        },
                        new
                        {
                            Id = 22,
                            Effort = 0.5,
                            Inactive = false,
                            Position = 3,
                            Title = "CSS Basics",
                            URL = "#"
                        },
                        new
                        {
                            Id = 33,
                            Effort = 2.0,
                            Inactive = false,
                            Position = 4,
                            Title = "Ruby: What extend and include do",
                            URL = "#"
                        },
                        new
                        {
                            Id = 44,
                            Effort = 0.5,
                            Inactive = false,
                            Position = 5,
                            Title = "Rules of thumb against flaky specs",
                            URL = "#"
                        },
                        new
                        {
                            Id = 55,
                            Effort = 1.5,
                            Inactive = false,
                            Position = 6,
                            Title = "How to use API",
                            URL = "#"
                        },
                        new
                        {
                            Id = 66,
                            Effort = 2.0,
                            Inactive = false,
                            Position = 7,
                            Title = "Linux",
                            URL = "https://makandracards.com/makandra-devops-curriculum/509339-linux-2-pt"
                        },
                        new
                        {
                            Id = 77,
                            Effort = 1.0,
                            Inactive = false,
                            Position = 7,
                            Title = "Linux file system",
                            URL = "https://makandracards.com/makandra-devops-curriculum/511179-linux-filesystems-und-verschluesselung-2-pt"
                        },
                        new
                        {
                            Id = 88,
                            Effort = 1.0,
                            Inactive = false,
                            Position = 8,
                            Title = "Resource use",
                            URL = "https://makandracards.com/makandra-devops-curriculum/509415-ressourcen-nutzung-1-pt"
                        },
                        new
                        {
                            Id = 99,
                            Effort = 0.5,
                            Inactive = false,
                            Position = 9,
                            Title = "Linux Kernal parameter",
                            URL = "https://makandracards.com/makandra-devops-curriculum/511330-linux-kernel-parameter-0-5-pt"
                        },
                        new
                        {
                            Id = 100,
                            Effort = 4.0,
                            Inactive = false,
                            Position = 10,
                            Title = "Network",
                            URL = "https://makandracards.com/makandra-devops-curriculum/509341-netzwerke-4-pt"
                        });
                });

            modelBuilder.Entity("Trainee_Tracker.Models.LessonAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ExpectedProcessingDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TraineeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("TraineeId");

                    b.ToTable("LessonAssignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpectedProcessingDate = new DateOnly(2026, 6, 24),
                            LessonId = 11,
                            Position = 2,
                            Status = 3,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExpectedProcessingDate = new DateOnly(2026, 6, 25),
                            LessonId = 22,
                            Position = 3,
                            Status = 3,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 3,
                            ExpectedProcessingDate = new DateOnly(2026, 6, 26),
                            LessonId = 33,
                            Position = 4,
                            Status = 5,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 4,
                            ExpectedProcessingDate = new DateOnly(2026, 6, 26),
                            LessonId = 44,
                            Position = 5,
                            Status = 3,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 5,
                            ExpectedProcessingDate = new DateOnly(2026, 6, 27),
                            LessonId = 55,
                            Position = 6,
                            Status = 2,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 6,
                            ExpectedProcessingDate = new DateOnly(2026, 6, 28),
                            LessonId = 66,
                            Position = 7,
                            Status = 2,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 7,
                            ExpectedProcessingDate = new DateOnly(2026, 6, 30),
                            LessonId = 77,
                            Position = 8,
                            Status = 1,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 8,
                            ExpectedProcessingDate = new DateOnly(2026, 6, 30),
                            LessonId = 88,
                            Position = 9,
                            Status = 1,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 9,
                            ExpectedProcessingDate = new DateOnly(2026, 7, 1),
                            LessonId = 99,
                            Position = 10,
                            Status = 0,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 10,
                            ExpectedProcessingDate = new DateOnly(2026, 7, 1),
                            LessonId = 100,
                            Position = 11,
                            Status = 0,
                            TraineeId = 1
                        });
                });

            modelBuilder.Entity("Trainee_Tracker.Models.LessonFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ActualEffort")
                        .HasColumnType("REAL");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MentorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PriorKnowledge")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TraineeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.HasIndex("TraineeId");

                    b.ToTable("LessonFeedbacks");
                });

            modelBuilder.Entity("Trainee_Tracker.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Closed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Role").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Trainee_Tracker.Models.Admin", b =>
                {
                    b.HasBaseType("Trainee_Tracker.Models.User");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("Trainee_Tracker.Models.Mentor", b =>
                {
                    b.HasBaseType("Trainee_Tracker.Models.User");

                    b.HasDiscriminator().HasValue("Mentor");
                });

            modelBuilder.Entity("Trainee_Tracker.Models.Trainee", b =>
                {
                    b.HasBaseType("Trainee_Tracker.Models.User");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartingDate")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Trainee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Closed = false,
                            Email = "testtrainee@makandra.de",
                            HashedPassword = "$2a$11$gwKInbiJCeTyAVYKfvR7b.dypqiFm.BmbeAzX.hlmGfGnLML0Cg9C",
                            Name = "Test Trainee",
                            EndDate = new DateOnly(2027, 1, 1),
                            StartingDate = new DateOnly(2026, 6, 30)
                        });
                });

            modelBuilder.Entity("MentorTrainee", b =>
                {
                    b.HasOne("Trainee_Tracker.Models.Trainee", null)
                        .WithMany()
                        .HasForeignKey("AssignedTraineesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainee_Tracker.Models.Mentor", null)
                        .WithMany()
                        .HasForeignKey("MentorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trainee_Tracker.Models.LessonAssignment", b =>
                {
                    b.HasOne("Trainee_Tracker.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainee_Tracker.Models.Trainee", "Trainee")
                        .WithMany("Assignments")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("Trainee_Tracker.Models.LessonFeedback", b =>
                {
                    b.HasOne("Trainee_Tracker.Models.Mentor", "Mentor")
                        .WithMany()
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainee_Tracker.Models.Trainee", "Trainee")
                        .WithMany()
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mentor");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("Trainee_Tracker.Models.Trainee", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
