// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trainee_Tracker.Data;

#nullable disable

namespace Trainee_Tracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629183638_AddLessonAssignment")]
    partial class AddLessonAssignment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("MentorTrainee", b =>
                {
                    b.Property<int>("AssignedTraineesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MentorsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssignedTraineesId", "MentorsId");

                    b.HasIndex("MentorsId");

                    b.ToTable("MentorTrainee");
                });

            modelBuilder.Entity("Trainee_Tracker.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Effort")
                        .HasColumnType("REAL");

                    b.Property<bool>("Inactive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("Trainee_Tracker.Models.LessonAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ExpectedProcessingDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TraineeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("TraineeId");

                    b.ToTable("LessonAssignments");
                });

            modelBuilder.Entity("Trainee_Tracker.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Closed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Role").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Trainee_Tracker.Models.Admin", b =>
                {
                    b.HasBaseType("Trainee_Tracker.Models.User");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("Trainee_Tracker.Models.Mentor", b =>
                {
                    b.HasBaseType("Trainee_Tracker.Models.User");

                    b.HasDiscriminator().HasValue("Mentor");
                });

            modelBuilder.Entity("Trainee_Tracker.Models.Trainee", b =>
                {
                    b.HasBaseType("Trainee_Tracker.Models.User");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartingDate")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Trainee");
                });

            modelBuilder.Entity("MentorTrainee", b =>
                {
                    b.HasOne("Trainee_Tracker.Models.Trainee", null)
                        .WithMany()
                        .HasForeignKey("AssignedTraineesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainee_Tracker.Models.Mentor", null)
                        .WithMany()
                        .HasForeignKey("MentorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trainee_Tracker.Models.LessonAssignment", b =>
                {
                    b.HasOne("Trainee_Tracker.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainee_Tracker.Models.Trainee", "Trainee")
                        .WithMany("Assignments")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("Trainee_Tracker.Models.Trainee", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
