// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trainee_Tracker.Data;

#nullable disable

namespace Trainee_Tracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260712224203_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("MentorTrainee", b =>
                {
                    b.Property<int>("AssignedTraineesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MentorsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssignedTraineesId", "MentorsId");

                    b.HasIndex("MentorsId");

                    b.ToTable("MentorTrainee");

                    b.HasData(
                        new
                        {
                            AssignedTraineesId = 9,
                            MentorsId = 7
                        },
                        new
                        {
                            AssignedTraineesId = 10,
                            MentorsId = 7
                        },
                        new
                        {
                            AssignedTraineesId = 11,
                            MentorsId = 7
                        },
                        new
                        {
                            AssignedTraineesId = 11,
                            MentorsId = 8
                        },
                        new
                        {
                            AssignedTraineesId = 3,
                            MentorsId = 5
                        },
                        new
                        {
                            AssignedTraineesId = 1,
                            MentorsId = 5
                        },
                        new
                        {
                            AssignedTraineesId = 1,
                            MentorsId = 4
                        });
                });

            modelBuilder.Entity("Trainee_Tracker.Models.Curriculum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Curricula");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "makandra Curriculum"
                        },
                        new
                        {
                            Id = 2,
                            Title = "makandra DevOps-Curriculum"
                        });
                });

            modelBuilder.Entity("Trainee_Tracker.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurriculumId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Effort")
                        .HasColumnType("REAL");

                    b.Property<bool>("Inactive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurriculumId");

                    b.ToTable("Lessons");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            CurriculumId = 1,
                            Effort = 3.5,
                            Inactive = false,
                            Position = 1,
                            Title = "Fundamentals of Web Development",
                            URL = "https://makandracards.com/makandra-devops-curriculum/509333-grundlagen-aus-der-web-entwicklung-3-5-pt"
                        },
                        new
                        {
                            Id = 111,
                            CurriculumId = 1,
                            Effort = 0.5,
                            Inactive = false,
                            Position = 6,
                            Title = "SSH",
                            URL = "https://makandracards.com/makandra-devops-curriculum/511181-ssh-0-5-pt"
                        },
                        new
                        {
                            Id = 22,
                            CurriculumId = 1,
                            Effort = 2.0,
                            Inactive = false,
                            Position = 3,
                            Title = "Virtualization",
                            URL = "https://makandracards.com/makandra-devops-curriculum/509340-virtualisierung-2-pt"
                        },
                        new
                        {
                            Id = 33,
                            CurriculumId = 1,
                            Effort = 2.0,
                            Inactive = false,
                            Position = 4,
                            Title = "Lxc/LXD",
                            URL = "https://makandracards.com/makandra-devops-curriculum/517382-lxc-lxd-2-pt"
                        },
                        new
                        {
                            Id = 44,
                            CurriculumId = 1,
                            Effort = 1.0,
                            Inactive = false,
                            Position = 5,
                            Title = "A Brief Introduction to Docker and Containers ",
                            URL = "https://makandracards.com/makandra-devops-curriculum/523491-kurze-einfuehrung-docker-und-container-1-pt"
                        },
                        new
                        {
                            Id = 55,
                            CurriculumId = 1,
                            Effort = 0.5,
                            Inactive = false,
                            Position = 6,
                            Title = "Firewalling with iptables",
                            URL = "https://makandracards.com/makandra-devops-curriculum/531475-firewalling-mit-iptables-0-5-pt"
                        },
                        new
                        {
                            Id = 66,
                            CurriculumId = 1,
                            Effort = 2.0,
                            Inactive = false,
                            Position = 2,
                            Title = "Linux",
                            URL = "https://makandracards.com/makandra-devops-curriculum/509339-linux-2-pt"
                        },
                        new
                        {
                            Id = 77,
                            CurriculumId = 1,
                            Effort = 1.0,
                            Inactive = false,
                            Position = 7,
                            Title = "Linux file system",
                            URL = "https://makandracards.com/makandra-devops-curriculum/511179-linux-filesystems-und-verschluesselung-2-pt"
                        },
                        new
                        {
                            Id = 88,
                            CurriculumId = 1,
                            Effort = 1.0,
                            Inactive = false,
                            Position = 8,
                            Title = "Resource use",
                            URL = "https://makandracards.com/makandra-devops-curriculum/509415-ressourcen-nutzung-1-pt"
                        },
                        new
                        {
                            Id = 99,
                            CurriculumId = 1,
                            Effort = 0.5,
                            Inactive = false,
                            Position = 9,
                            Title = "Linux Kernal parameter",
                            URL = "https://makandracards.com/makandra-devops-curriculum/511330-linux-kernel-parameter-0-5-pt"
                        },
                        new
                        {
                            Id = 100,
                            CurriculumId = 1,
                            Effort = 4.0,
                            Inactive = false,
                            Position = 10,
                            Title = "Network",
                            URL = "https://makandracards.com/makandra-devops-curriculum/509341-netzwerke-4-pt"
                        },
                        new
                        {
                            Id = 222,
                            CurriculumId = 1,
                            Effort = 2.5,
                            Inactive = false,
                            Position = 11,
                            Title = "HTTP Protocoll and Webserver",
                            URL = "https://makandracards.com/makandra-devops-curriculum/519412-http-protokoll-und-webserver-2-5-pt"
                        });
                });

            modelBuilder.Entity("Trainee_Tracker.Models.LessonAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("ExpectedProcessingDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TraineeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("TraineeId");

                    b.ToTable("LessonAssignments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExpectedProcessingDate = new DateOnly(2026, 6, 29),
                            LessonId = 11,
                            Position = 2,
                            Status = 3,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 2,
                            ExpectedProcessingDate = new DateOnly(2026, 6, 29),
                            LessonId = 22,
                            Position = 3,
                            Status = 3,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 3,
                            ExpectedProcessingDate = new DateOnly(2026, 6, 29),
                            LessonId = 33,
                            Position = 4,
                            Status = 3,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 4,
                            ExpectedProcessingDate = new DateOnly(2026, 6, 30),
                            LessonId = 44,
                            Position = 5,
                            Status = 3,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 5,
                            ExpectedProcessingDate = new DateOnly(2026, 6, 30),
                            LessonId = 55,
                            Position = 6,
                            Status = 2,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 6,
                            ExpectedProcessingDate = new DateOnly(2026, 7, 1),
                            LessonId = 66,
                            Position = 7,
                            Status = 2,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 7,
                            ExpectedProcessingDate = new DateOnly(2026, 7, 1),
                            LessonId = 77,
                            Position = 8,
                            Status = 1,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 8,
                            ExpectedProcessingDate = new DateOnly(2026, 7, 1),
                            LessonId = 88,
                            Position = 9,
                            Status = 1,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 9,
                            ExpectedProcessingDate = new DateOnly(2026, 7, 2),
                            LessonId = 99,
                            Position = 10,
                            Status = 0,
                            TraineeId = 1
                        },
                        new
                        {
                            Id = 10,
                            ExpectedProcessingDate = new DateOnly(2026, 7, 3),
                            LessonId = 100,
                            Position = 11,
                            Status = 0,
                            TraineeId = 3
                        },
                        new
                        {
                            Id = 11,
                            ExpectedProcessingDate = new DateOnly(2026, 6, 29),
                            LessonId = 11,
                            Position = 2,
                            Status = 3,
                            TraineeId = 3
                        },
                        new
                        {
                            Id = 12,
                            ExpectedProcessingDate = new DateOnly(2026, 6, 29),
                            LessonId = 22,
                            Position = 3,
                            Status = 3,
                            TraineeId = 3
                        },
                        new
                        {
                            Id = 13,
                            ExpectedProcessingDate = new DateOnly(2026, 6, 29),
                            LessonId = 33,
                            Position = 4,
                            Status = 3,
                            TraineeId = 3
                        },
                        new
                        {
                            Id = 14,
                            ExpectedProcessingDate = new DateOnly(2026, 6, 30),
                            LessonId = 44,
                            Position = 6,
                            Status = 3,
                            TraineeId = 3
                        },
                        new
                        {
                            Id = 15,
                            ExpectedProcessingDate = new DateOnly(2026, 6, 30),
                            LessonId = 55,
                            Position = 5,
                            Status = 2,
                            TraineeId = 3
                        },
                        new
                        {
                            Id = 16,
                            ExpectedProcessingDate = new DateOnly(2026, 7, 1),
                            LessonId = 66,
                            Position = 7,
                            Status = 2,
                            TraineeId = 3
                        },
                        new
                        {
                            Id = 17,
                            ExpectedProcessingDate = new DateOnly(2026, 7, 1),
                            LessonId = 77,
                            Position = 9,
                            Status = 2,
                            TraineeId = 3
                        },
                        new
                        {
                            Id = 18,
                            ExpectedProcessingDate = new DateOnly(2026, 7, 2),
                            LessonId = 88,
                            Position = 8,
                            Status = 1,
                            TraineeId = 3
                        },
                        new
                        {
                            Id = 19,
                            ExpectedProcessingDate = new DateOnly(2026, 7, 2),
                            LessonId = 99,
                            Position = 10,
                            Status = 1,
                            TraineeId = 3
                        },
                        new
                        {
                            Id = 20,
                            ExpectedProcessingDate = new DateOnly(2026, 7, 3),
                            LessonId = 100,
                            Position = 11,
                            Status = 0,
                            TraineeId = 3
                        },
                        new
                        {
                            Id = 21,
                            ExpectedProcessingDate = new DateOnly(2026, 7, 3),
                            LessonId = 111,
                            Position = 12,
                            Status = 0,
                            TraineeId = 3
                        },
                        new
                        {
                            Id = 22,
                            ExpectedProcessingDate = new DateOnly(2026, 7, 3),
                            LessonId = 222,
                            Position = 13,
                            Status = 0,
                            TraineeId = 3
                        });
                });

            modelBuilder.Entity("Trainee_Tracker.Models.LessonFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ActualEffort")
                        .HasColumnType("REAL");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LessonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MentorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PriorKnowledge")
                        .HasColumnType("TEXT");

                    b.Property<int>("TraineeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("MentorId");

                    b.HasIndex("TraineeId");

                    b.ToTable("LessonFeedbacks");
                });

            modelBuilder.Entity("Trainee_Tracker.Models.Rejection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RejectedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.ToTable("Rejections");
                });

            modelBuilder.Entity("Trainee_Tracker.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Closed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Role").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Trainee_Tracker.Models.Mentor", b =>
                {
                    b.HasBaseType("Trainee_Tracker.Models.User");

                    b.Property<int?>("CurriculumId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("CurriculumId");

                    b.HasDiscriminator().HasValue("Mentor");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Closed = false,
                            Email = "jelenacosic2@makandra.de",
                            HashedPassword = "$2a$11$gwKInbiJCeTyAVYKfvR7b.dypqiFm.BmbeAzX.hlmGfGnLML0Cg9C",
                            Name = "Jelena2 Mentor",
                            CurriculumId = 1
                        },
                        new
                        {
                            Id = 7,
                            Closed = false,
                            Email = "manfred.mental@makandra.de",
                            HashedPassword = "$2a$11$kce.fXXVmBy2n0DaoYUcuujmpl.lXCCgZC7WSoFT94B98q5FS.gMa",
                            Name = "Manfred Mental",
                            CurriculumId = 1
                        },
                        new
                        {
                            Id = 8,
                            Closed = false,
                            Email = "hans.hilfreich@makandra.de",
                            HashedPassword = "$2a$11$RirFsrHzwqEKO0Wr8sIiZuprcJ5Pz8y45bRGLltqSos0cePlhhLvC",
                            Name = "Hans Hilfreich",
                            CurriculumId = 1
                        });
                });

            modelBuilder.Entity("Trainee_Tracker.Models.Trainee", b =>
                {
                    b.HasBaseType("Trainee_Tracker.Models.User");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartingDate")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Trainee");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Closed = false,
                            Email = "jelenacosic3@makandra.de",
                            HashedPassword = "$2a$11$gwKInbiJCeTyAVYKfvR7b.dypqiFm.BmbeAzX.hlmGfGnLML0Cg9C",
                            Name = "Jelena3 Trainee",
                            EndDate = new DateOnly(1, 1, 1),
                            StartingDate = new DateOnly(1, 1, 1)
                        },
                        new
                        {
                            Id = 1,
                            Closed = false,
                            Email = "torstentrainee@makandra.de",
                            HashedPassword = "$2a$11$gwKInbiJCeTyAVYKfvR7b.dypqiFm.BmbeAzX.hlmGfGnLML0Cg9C",
                            Name = "Torsten Trainee",
                            EndDate = new DateOnly(2027, 1, 1),
                            StartingDate = new DateOnly(2026, 6, 30)
                        },
                        new
                        {
                            Id = 3,
                            Closed = false,
                            Email = "tildatrainee@makandra.de",
                            HashedPassword = "$2a$11$gwKInbiJCeTyAVYKfvR7b.dypqiFm.BmbeAzX.hlmGfGnLML0Cg9C",
                            Name = "Tilda Trainee",
                            EndDate = new DateOnly(2027, 1, 1),
                            StartingDate = new DateOnly(2026, 7, 1)
                        },
                        new
                        {
                            Id = 9,
                            Closed = false,
                            Email = "vanessa.vital@makandra.de",
                            HashedPassword = "$2a$11$OvYPz8FkuxXJe7WyPIHpzOc1bi5beKtsB2WYXBJlVDqsNRCJatfzK",
                            Name = "Vanessa Vital",
                            EndDate = new DateOnly(2027, 3, 31),
                            StartingDate = new DateOnly(2026, 7, 17)
                        },
                        new
                        {
                            Id = 10,
                            Closed = false,
                            Email = "stefan.schnupfen@makandra.de",
                            HashedPassword = "$2a$11$1YdXfUYVKPO7t0wmYKVirOq4mYR4k/sxxO6YlY7c2CdSO50yRSqGW",
                            Name = "Stefan Schnupfen",
                            EndDate = new DateOnly(2026, 10, 31),
                            StartingDate = new DateOnly(2026, 5, 1)
                        },
                        new
                        {
                            Id = 11,
                            Closed = false,
                            Email = "ursula.urlaub@makandra.de",
                            HashedPassword = "$2a$11$aemTP4KrL44P1z23XD39u.7nnd3zoXeME0PFZzVkQPTEmmK/fVqRm",
                            Name = "Ursula Urlaub",
                            EndDate = new DateOnly(2026, 7, 31),
                            StartingDate = new DateOnly(2026, 1, 1)
                        });
                });

            modelBuilder.Entity("Trainee_Tracker.Models.Admin", b =>
                {
                    b.HasBaseType("Trainee_Tracker.Models.Mentor");

                    b.HasDiscriminator().HasValue("Admin");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Closed = false,
                            Email = "jelenacosic1@makandra.de",
                            HashedPassword = "$2a$11$gwKInbiJCeTyAVYKfvR7b.dypqiFm.BmbeAzX.hlmGfGnLML0Cg9C",
                            Name = "Jelena3 Admin"
                        },
                        new
                        {
                            Id = 6,
                            Closed = false,
                            Email = "admin@makandra.de",
                            HashedPassword = "$2a$11$NWoCmWYUtc4Kj0eDILuyxOjWj0GReHhxe2bh6Crx1QR4heeWH1EcO",
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("MentorTrainee", b =>
                {
                    b.HasOne("Trainee_Tracker.Models.Trainee", null)
                        .WithMany()
                        .HasForeignKey("AssignedTraineesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainee_Tracker.Models.Mentor", null)
                        .WithMany()
                        .HasForeignKey("MentorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trainee_Tracker.Models.Lesson", b =>
                {
                    b.HasOne("Trainee_Tracker.Models.Curriculum", null)
                        .WithMany("_Lessons")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trainee_Tracker.Models.LessonAssignment", b =>
                {
                    b.HasOne("Trainee_Tracker.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainee_Tracker.Models.Trainee", "Trainee")
                        .WithMany("Assignments")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("Trainee_Tracker.Models.LessonFeedback", b =>
                {
                    b.HasOne("Trainee_Tracker.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainee_Tracker.Models.Mentor", "Mentor")
                        .WithMany()
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainee_Tracker.Models.Trainee", "Trainee")
                        .WithMany()
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Mentor");

                    b.Navigation("Trainee");
                });

            modelBuilder.Entity("Trainee_Tracker.Models.Rejection", b =>
                {
                    b.HasOne("Trainee_Tracker.Models.LessonAssignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("Trainee_Tracker.Models.Mentor", b =>
                {
                    b.HasOne("Trainee_Tracker.Models.Curriculum", "Curriculum")
                        .WithMany("Mentors")
                        .HasForeignKey("CurriculumId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Curriculum");
                });

            modelBuilder.Entity("Trainee_Tracker.Models.Curriculum", b =>
                {
                    b.Navigation("Mentors");

                    b.Navigation("_Lessons");
                });

            modelBuilder.Entity("Trainee_Tracker.Models.Trainee", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
