// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trainee_Tracker.Data;

#nullable disable

namespace Trainee_Tracker.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("MentorTrainee", b =>
                {
                    b.Property<int>("AssignedTraineesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MentorsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AssignedTraineesId", "MentorsId");

                    b.HasIndex("MentorsId");

                    b.ToTable("MentorTrainee");
                });

            modelBuilder.Entity("Trainee_Tracker.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Closed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Trainee_Tracker.Models.Admin", b =>
                {
                    b.HasBaseType("Trainee_Tracker.Models.User");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("Trainee_Tracker.Models.Mentor", b =>
                {
                    b.HasBaseType("Trainee_Tracker.Models.User");

                    b.HasDiscriminator().HasValue("Mentor");
                });

            modelBuilder.Entity("Trainee_Tracker.Models.Trainee", b =>
                {
                    b.HasBaseType("Trainee_Tracker.Models.User");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartingDate")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Trainee");
                });

            modelBuilder.Entity("MentorTrainee", b =>
                {
                    b.HasOne("Trainee_Tracker.Models.Trainee", null)
                        .WithMany()
                        .HasForeignKey("AssignedTraineesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Trainee_Tracker.Models.Mentor", null)
                        .WithMany()
                        .HasForeignKey("MentorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
